### ISSUE TITLE
`a.push is not a function` errors

### ISSUE THREAD

**Issue by RDIL** [thepeacockproject/Peacock#479]
### Discussed in https://github.com/thepeacockproject/Peacock/discussions/474

<div type='discussions-op-text'>

<sup>Originally posted by **thecatontheceiling** June 21, 2024</sup>
Even if I add only one single space to one file, whenever I compile with `yarn install`, `yarn build` and `yarn optimize`, it always ends up breaking save functionality in some way.

![image](https://github.com/thepeacockproject/Peacock/assets/75037904/474cb20e-1404-499f-a05b-b41f783ab40a)
It spams these errors, usually when I've been compromised in-game but it can also happen in other situations. 

Thank you for reading :)
I hope my Windows install isn't fucked or something.

I have attached the outputted chunk0.js file here:
https://gofile.io/d/zzcqzT
https://gofile.io/d/pPTjwY</div>

**Comment by grappigegovert** [comment]
> Alright I tried compromising myself in Miami, Isle of sgail, the final test, paris and santa fortuna, only compromising myself in Sapienza causes these errors to occur.

Adding this comment here

**Comment by thecatontheceiling** [comment]
I said "save functionality" because general game jankiness with save files coincided with the first time I noticed these errors and assumed it was Peacock but I'm pretty sure this has nothing to do with save files

**Comment by grappigegovert** [comment]
Fixed in 0f9c41b55ea5832f1905f66cd46f20a6e365f9fd

**Comment by thecatontheceiling** [comment]
The errors are not fixed on my end. I deleted node_modules and ran `yarn install` to update statemachineparser but I am still getting the same errors in console

**Comment by thecatontheceiling** [comment]
NVM, checked node_modules manually and it just re-added the broken version again instead of getting latest :/

how the fuck do i clear the cache yarn uses or whatever

**Comment by grappigegovert** [comment]
Are you still on `v7`? the fix is only on `master` right now.

**Comment by thecatontheceiling** [comment]
maybe maybe not
